services:
  postgres:
    ports:
      - "5432:5432"
  
  kafka:
    ports:
      - "9092:9092"

  caddy:
    build:
      context: caddy
      dockerfile: Containerfile
      args:
        CADDY_VERSION: latest
        DOMAIN_NAME: ${DOMAIN_NAME}
        N8N_SUBDOMAIN: ${N8N_SUBDOMAIN_NAME}
        KAFKA_SUBDOMAIN: ${KAFKA_SUBDOMAIN_NAME}
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - caddy_data:/data
    depends_on:
      n8n:
        condition: service_healthy
      kafka-ui:
        condition: service_healthy

volumes:
  caddy_data:
    external: true
  n8n_data:
    external: true
  n8n_local_files:
    external: true
  postgres_data:
    external: true
